<?php
$typeArr[1] = '公开课程';
$typeArr[2] = '企业内训';
$typeArr[3] = '个人微训';
$typeArr[4] = '师资队伍';
$typeArr[5] = '许愿树';
$typeArr[6] = '联系我们';
$typeArr[7] = '生产管理';
$typeArr[8] = '财务管理';
$typeArr[9] = '人力资源';
$typeArr[10] = '职业素养';
$typeArr[11] = '商业地产';
$typeArr[12] = '国际贸易';
$typeArr[13] = '综合管理';
$typeArr[14] = '客户服务';
$typeArr[15] = '生产管理';
$typeArr[16] = '财务管理';
$typeArr[17] = '人力资源';
$typeArr[18] = '职业素养';
$typeArr[19] = '商业地产';
$typeArr[20] = '国际贸易';
$typeArr[21] = '综合管理';
$typeArr[22] = '客户服务';
$typeArr[23] = '合作客户';
$typeArr[24] = '新闻资讯';
?>