<?php
$z[0]=Array("arcurl","",61,76);
$z[1]=Array("teacher","",87,103);
$z[2]=Array("name","",107,120);
$z[3]=Array("start_date","",425,468);
$z[3][4]['function']="MyDate('',@me)";
$z[4]=Array("location","",543,560);
$z[5]=Array("price","",635,649);
$z[6]=Array("target","",788,845);
$z[6][4]['function']="cn_substrR(html2text(@me),100)";
$z[7]=Array("start_date","",1217,1260);
$z[7][4]['function']="MyDate('',@me)";
$z[8]=Array("end_date","",1333,1374);
$z[8][4]['function']="MyDate('',@me)";
$z[9]=Array("id","",1504,1515);
$z[10]=Array("typeid","",1523,1538);

?>