<div class="bao">
                <div class="ttt"><a href="[field:arcurl/]">讲师：[field:teacher/] 《[field:name/]》</a></div>
                <div class="kais"></div>
                <div class="kaiz">
                    <div class="mqq">
                        <ul>开课时间：[field:start_date function=MyDate('',@me)/]</ul>
                        <dl>开课地点：[field:location/]</dl>
                        <dt>课程价格：￥[field:price/]元</dt>
                        <br/>
                        <dd>课程目标：[field:target/]</dd>
                        <span >状  态：
                            <b onload="set_state('[field:start_date function=MyDate('',@me)/]','[field:end_date function=MyDate('',@me)/]');"></b>
                        </span>
                    </div>
                    <div class="mingg">
                        <a href="">
                            <img src="/images/common/lijibaoming.jpg" alt=""/>
                        </a>
                    </div>
                </div>
                <div class="kaid"></div>
            </div>
            <script type="text/javascript">