<tr >
                    <td class="name"><a href="[field:arcurl/]">《[field:name/]》</a></td>
                    <td class="time">[field:start_date function=MyDate('y-m-d',@me)/]</td>
                    <td class="location">[field:location /]</td>
                    <td class="price">￥[field:price/]</td>
                    <td class="opration"><a href="#"><img src="/images/common/ming.jpg" alt=""/></a></td>
                </tr>