<div class="bao">
                <div class="ttt"><a href="[field:arcurl/]">[field:title/]</a></div>
                <div class="kais"></div>
                <div class="kaiz">
                    <div class="mqq">
                        [field:description function='cn_substrR(html2text(@me),200)'/]
                    </div>
                </div>
                <div class="kaid">
                </div>
            </div>