<?php
$z[0]=Array("top","\r\n  <m:item name='国内订单' link='shops_operations.php' rank='sys_Data' target='main' class='nrmxgl' />\r\n  <m:item name='国外订单' link='shops_operations.php?lang=2' rank='sys_Data' target='main' class='nrmxgl' />\r\n",51,364);
$z[0][4]['item']="1_";
$z[0][4]['name']="订单管理";
$z[0][4]['display']="block";
$z[0][4]['rank']="sys_Data";
$z[0][4]['class']="pdmx";
$z[1]=Array("top","\r\n  <m:item name='支付接口设置' link='sys_payment.php' rank='sys_Data' target='main' class='nrmxgl' />\r\n  <m:item name='配送方式设置' link='shops_delivery.php' rank='sys_Data' target='main' class='nrmxgl' />\r\n",366,678);
$z[1][4]['item']="1_";
$z[1][4]['name']="支付/配送";
$z[1][4]['display']="block";
$z[1][4]['rank']="sys_Data";
$z[1][4]['class']="pdmx";
$z[2]=Array("top","\r\n  <m:item name='内容模型管理' link='mychannel_main.php' rank='c_List' target='main' class='nrmxgl' />\r\n",680,905);
$z[2][4]['item']="1_";
$z[2][4]['name']="频道模型";
$z[2][4]['display']="block";
$z[2][4]['rank']="t_List,t_AccList,c_List,temp_One";
$z[2][4]['class']="pdmx";

?>