<?php
$z[0]=Array("arcurl","",61,76);
$z[1]=Array("teacher","",87,103);
$z[2]=Array("name","",107,120);
$z[3]=Array("start_date","",449,492);
$z[3][4]['function']="MyDate('',@me)";
$z[4]=Array("location","",550,567);
$z[5]=Array("target","",625,640);
$z[6]=Array("target","",767,782);
$z[7]=Array("start_date","",1155,1198);
$z[7][4]['function']="MyDate('',@me)";
$z[8]=Array("end_date","",1271,1312);
$z[8][4]['function']="MyDate('',@me)";
$z[9]=Array("id","",1442,1453);
$z[10]=Array("typeid","",1461,1476);

?>