<?php
$z[0]=Array("arcurl","",61,76);
$z[1]=Array("teacher","",87,103);
$z[2]=Array("name","",107,120);
$z[3]=Array("start_date","",464,507);
$z[3][4]['function']="MyDate('',@me)";
$z[4]=Array("location","",584,601);
$z[5]=Array("price","",678,692);
$z[6]=Array("target","",839,896);
$z[6][4]['function']="cn_substrR(html2text(@me),200)";
$z[7]=Array("start_date","",1326,1369);
$z[7][4]['function']="MyDate('',@me)";
$z[8]=Array("end_date","",1442,1483);
$z[8][4]['function']="MyDate('',@me)";
$z[9]=Array("id","",1613,1624);
$z[10]=Array("typeid","",1632,1647);

?>