<div class="tz">
            <div class="si">
                <a href="[field:arcurl/]">
                    <div class="picc"><img src="[field:litpic/]" alt="[field:name/]" ></div>
                    <div class="lao">[field:name/]</div>
                    <div class="jie">[field:breif function='cn_substrR(html2text(@me),40)'/]...</div>
                    <div class="zi"><a href="tencent://message/?uin=[field:conntact/]&Site=Customer service 1&Menu=yes">[点击在线咨询]</a></div>
                </a>
            </div>
        </div>