<?php
$z[0]=Array("arcurl","",61,76);
$z[1]=Array("teacher","",87,103);
$z[2]=Array("name","",107,120);
$z[3]=Array("start_date","",464,507);
$z[3][4]['function']="MyDate('',@me)";
$z[4]=Array("location","",584,601);
$z[5]=Array("price","",678,692);
$z[6]=Array("target","",839,854);
$z[7]=Array("start_date","",1244,1287);
$z[7][4]['function']="MyDate('',@me)";
$z[8]=Array("end_date","",1360,1401);
$z[8][4]['function']="MyDate('',@me)";
$z[9]=Array("id","",1531,1542);
$z[10]=Array("typeid","",1550,1565);

?>