
-----------------------------------------------
<m:top item='1_' name='订单管理' display='block' rank='sys_Data' class='pdmx'>
  <m:item name='订单' link='shops_operations.php' rank='sys_Data' target='main' class='nrmxgl' />
</m:top>
<m:top item='1_' name='支付/配送' display='block' rank='sys_Data' class='pdmx'>
  <m:item name='支付接口设置' link='sys_payment.php' rank='sys_Data' target='main' class='nrmxgl' />
  <m:item name='配送方式设置' link='shops_delivery.php' rank='sys_Data' target='main' class='nrmxgl' />
</m:top>
<m:top item='1_' name='频道模型' display='block' rank='t_List,t_AccList,c_List,temp_One' class='pdmx'>
  <m:item name='内容模型管理' link='mychannel_main.php' rank='c_List' target='main' class='nrmxgl' />
</m:top>
-----------------------------------------------
