<?php
$z[0]=Array("arcurl","",61,76);
$z[1]=Array("teacher","",87,103);
$z[2]=Array("name","",107,120);
$z[3]=Array("start_date","",794,837);
$z[3][4]['function']="MyDate('',@me)";
$z[4]=Array("location","",887,904);
$z[5]=Array("price","",957,971);
$z[6]=Array("target","",1055,1070);
$z[7]=Array("start_date","",1261,1304);
$z[7][4]['function']="MyDate('',@me)";
$z[8]=Array("end_date","",1377,1418);
$z[8][4]['function']="MyDate('',@me)";
$z[9]=Array("id","",1548,1559);
$z[10]=Array("typeid","",1567,1582);

?>