<?php
$z[0]=Array("field","",69,87);
$z[0][4]['name']="title";
$z[1]=Array("global","",88,113);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",160,189);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",228,254);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",573,607);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",675,703);
$z[5][4]['name']="position";
$z[6]=Array("arclist","\n                        <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n                        ",989,1139);
$z[6][4]['typeid']="24";
$z[6][4]['row']="9";
$z[7]=Array("arclist","\n                        <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n                        ",1605,1796);
$z[7][4]['getall']="1";
$z[7][4]['typeid']="1,2,3";
$z[7][4]['flag']="c";
$z[7][4]['row']="7";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("field","",2680,2700);
$z[8][4]['name']="content";
$z[9]=Array("include","",2776,2812);
$z[9][4]['filename']="footer.htm";

?>