<?php
$z[0]=Array("global","",69,94);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",141,170);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",209,235);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",554,588);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",656,684);
$z[4][4]['name']="position";
$z[5]=Array("arclist","\n                        <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n                        ",970,1120);
$z[5][4]['typeid']="24";
$z[5][4]['row']="9";
$z[6]=Array("arclist","\n                        <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n                        ",1586,1766);
$z[6][4]['typeid']="1,2,3";
$z[6][4]['flag']="c";
$z[6][4]['row']="7";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("field","",2650,2670);
$z[7][4]['name']="content";
$z[8]=Array("include","",2746,2782);
$z[8][4]['filename']="footer.htm";

?>