<?php
$z[0]=Array("arcurl","",61,76);
$z[1]=Array("teacher","",87,103);
$z[2]=Array("name","",107,120);
$z[3]=Array("start_date","",295,338);
$z[3][4]['function']="MyDate('',@me)";
$z[4]=Array("location","",388,405);
$z[5]=Array("price","",458,472);
$z[6]=Array("target","",556,571);
$z[7]=Array("start_date","",762,805);
$z[7][4]['function']="MyDate('',@me)";
$z[8]=Array("end_date","",878,919);
$z[8][4]['function']="MyDate('',@me)";
$z[9]=Array("arcid","",1049,1063);
$z[10]=Array("typeid","",1071,1086);

?>