<?php
$z[0]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",71,189);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",203,321);
$z[1][4]['typeid']="2";
$z[2]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",335,453);
$z[2][4]['typeid']="3";
$z[3]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">讲师风采</a></li>\r\n            ",625,738);
$z[3][4]['typeid']="4";
$z[4]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">典型客户</a></li>\r\n            ",752,866);
$z[4][4]['typeid']="23";
$z[5]=Array("type","\r\n            <li class=\"s\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",880,1008);
$z[5][4]['typeid']="6";

?>