<?php
$z[0]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",71,189);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",203,321);
$z[1][4]['typeid']="2";
$z[2]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",335,453);
$z[2][4]['typeid']="3";
$z[3]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">在线报名</a></li>\r\n            ",467,581);
$z[3][4]['typeid']="25";
$z[4]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">讲师风采</a></li>\r\n            ",595,708);
$z[4][4]['typeid']="4";
$z[5]=Array("type","\r\n            <li><a href=\"[field:typelink/]\">典型客户</a></li>\r\n            ",722,836);
$z[5][4]['typeid']="23";
$z[6]=Array("type","\r\n            <li class=\"s\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",850,978);
$z[6][4]['typeid']="6";

?>