<?php
$z[0]=Array("global","",86,111);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",159,188);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",228,254);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",580,614);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",712,749);
$z[4][4]['filename']="sidebar.htm";
$z[5]=Array("var","",1220,1242);
$z[5][4]['name']="course_type";
$z[6]=Array("include","",6695,6731);
$z[6][4]['filename']="footer.htm";

?>