<?php
$z[0]=Array("field","",73,91);
$z[0][4]['name']="title";
$z[1]=Array("global","",92,117);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",165,194);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",234,260);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",512,546);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",616,644);
$z[5][4]['name']="position";
$z[6]=Array("arclist","\r\n                        <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                        ",927,1120);
$z[6][4]['typeid']="1,2,3";
$z[6][4]['getall']="1";
$z[6][4]['flag']="c";
$z[6][4]['row']="7";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("arclist","\r\n                <div class=\"si\">\r\n                    <div class=\"picc\"><img src=\"[field:litpic/]\" alt=\"[field:name/]\" /></div>\r\n                    <div class=\"lao\">[field:name/]</div>\r\n                    <div class=\"jie\">\r\n                        [field:breif function='cn_substrR(html2text(@me),40)'/]…\r\n                    </div>\r\n                </div>\r\n                ",1395,1885);
$z[7][4]['typeid']="4";
$z[7][4]['flag']="c";
$z[7][4]['row']="3";
$z[7][4]['orderby']="weight";
$z[7][4]['addfields']="name,breif";
$z[7][4]['channelid']="15";
$z[8]=Array("field","",2552,2570);
$z[8][4]['name']="title";
$z[9]=Array("arclist","\r\n                    <li class=\"op_li\">\r\n                        <img src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                        <p>[field:title/]</p>\r\n                    </li>\r\n                    ",2858,3114);
$z[9][4]['orderby']="weight";
$z[10]=Array("include","",3232,3268);
$z[10][4]['filename']="footer.htm";

?>