<?php
$z[0]=Array("field","",73,91);
$z[0][4]['name']="title";
$z[1]=Array("global","",92,117);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",165,194);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",234,260);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",586,620);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",690,718);
$z[5][4]['name']="position";
$z[6]=Array("arclist","\r\n                        <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                        ",1001,1194);
$z[6][4]['typeid']="1,2,3";
$z[6][4]['getall']="1";
$z[6][4]['flag']="c";
$z[6][4]['row']="7";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("arclist","\r\n            <div class=\"bao\">\r\n                <div class=\"ttt\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n                <div class=\"kais\"></div>\r\n                <div class=\"kaiz\">\r\n                    <div class=\"mqq\">\r\n                        [field:description function='cn_substrR(html2text(@me),200)'/]\r\n                    </div>\r\n                </div>\r\n                <div class=\"kaid\">\r\n                </div>\r\n            </div>\r\n            ",1894,2414);
$z[7][4]['row']="7";
$z[7][4]['orderby']="weight";
$z[8]=Array("pagelist","",2491,2570);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="7";
$z[8][4]['sitelang']="cn";
$z[9]=Array("include","",3294,3330);
$z[9][4]['filename']="footer.htm";

?>