<?php
$z[0]=Array("field","",69,87);
$z[0][4]['name']="title";
$z[1]=Array("global","",88,113);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",160,189);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",228,254);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",573,607);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",675,703);
$z[5][4]['name']="position";
$z[6]=Array("arclist","\n		                <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n		                ",940,1078);
$z[6][4]['typeid']="24";
$z[6][4]['row']="9";
$z[7]=Array("arclist","\n                        <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\n                        ",1508,1673);
$z[7][4]['flag']="c";
$z[7][4]['row']="7";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("arclist","\n                    <tr >\n                        <td class=\"name\"><a href=\"[field:arcurl/]\">《[field:title/]》</a></td>\n                        <td class=\"time\">[field:start_date function=MyDate('y-m-d',@me)/]</td>\n                        <td class=\"location\">[field:location /]</td>\n                        <td class=\"price\">￥[field:price/]</td>\n                    </tr>\n                    ",3381,3892);
$z[8][4]['row']="7";
$z[8][4]['orderby']="pubdate";
$z[8][4]['addfields']="price,name,start_date,location";
$z[8][4]['channelid']="17";
$z[9]=Array("pagelist","",4032,4111);
$z[9][4]['listitem']="index,end,pre,next,pageno";
$z[9][4]['listsize']="7";
$z[9][4]['sitelang']="cn";
$z[10]=Array("include","",4213,4249);
$z[10][4]['filename']="footer.htm";

?>