<?php
$z[0]=Array("global","",73,98);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",146,175);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",215,241);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",567,601);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",671,699);
$z[4][4]['name']="position";
$z[5]=Array("include","",711,748);
$z[5][4]['filename']="sidebar.htm";
$z[6]=Array("list","\r\n            <div class=\"bao\">\r\n                <div class=\"ttt\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n                <div class=\"kais\"></div>\r\n                <div class=\"kaiz\">\r\n                    <div class=\"mqq\">\r\n                        [field:description function='cn_substrR(html2text(@me),200)'/]\r\n                    </div>\r\n                </div>\r\n                <div class=\"kaid\">\r\n                </div>\r\n            </div>\r\n            ",1313,1826);
$z[6][4]['page']="10";
$z[6][4]['infolen']="200";
$z[7]=Array("pagelist","",1903,1982);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="7";
$z[7][4]['sitelang']="cn";
$z[8]=Array("include","",2706,2742);
$z[8][4]['filename']="footer.htm";

?>