<?php
$z[0]=Array("channel","\r\n                    <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    ",250,401);
$z[0][4]['typeid']="1";
$z[0][4]['getall']="1";
$z[1]=Array("arclist","\r\n                    <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                    ",724,898);
$z[1][4]['typeid']="1,2,3";
$z[1][4]['flag']="c";
$z[1][4]['row']="7";
$z[1][4]['orderby']="pubdate";

?>