<?php
$z[0]=Array("field","",69,87);
$z[0][4]['name']="title";
$z[1]=Array("global","",88,113);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",160,189);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",229,255);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",577,611);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",679,707);
$z[5][4]['name']="position";
$z[6]=Array("include","",9330,9366);
$z[6][4]['filename']="footer.htm";

?>